### ISSUE TITLE
Latest B2STAGE version does not work with iRODS 4.1.10

### ISSUE THREAD

**Issue by chStaiger** [EUDAT-B2STAGE/B2STAGE-GridFTP#28]
Hello, 

I am trying to deploy the latest version of B2STAGE on Centos 7.3 and iRODS 4.1.10.
I ran into some issues:

Error while make:
```sh
/home/admincentos/B2STAGE-GridFTP/DSI/globus_gridftp_server_iRODS.c:706:5: error: too few arguments to function ‘clientLogin’
     status = clientLogin(iRODS_handle->conn);
     ^

/home/admincentos/B2STAGE-GridFTP/DSI/libirodsmap.c:46:5: error: too few arguments to function ‘clientLogin’
     rc = clientLogin(rcComm);
     ^
```

Fix:
```sh
rc = clientLogin(rcComm, NULL, NULL);
status = clientLogin(iRODS_handle->conn, NULL, NULL);
```
The iRODS DSI then compiles. With some minor issues:
- setup.sh needs to be updated (it still contains an old export `export IRODS_40_COMPAT=""`)
- The destination exports are ignored completely. All binaries are in the B2STAGE-GrisFTP folder and not in the iRODS_DI folder

When starting the gridFTP server the following error pops up:
```sh
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/admincentos/B2STAGE-GridFTP/"
export LD_PRELOAD="$LD_PRELOAD:/usr/lib64/libglobus_gridftp_server.so:/home/admincentos/B2STAGE-GridFTP/libglobus_gridftp_server_iRODS.so"

/etc/init.d/globus-gridftp-server restart
b2stage-centos globus-gridftp-server[3157]: globus_extension_module: Couldn't dlopen libglobus_gridftp_server_iRODS_gcc64.so in /usr/lib64 (or LD_LIBRARY_PATH): file not found
```

This can be fixed with a symlink:
```
ln -s /usr/lib64/libglobus_gridftp_server_iRODS_gcc64.so -> /home/admincentos/B2STAGE-GridFTP/libglobus_gridftp_server_iRODS.so
```
After that the gridFTP server is up and running again, however, the connection between the server and iRODS does not work correctly.

```sh
[admincentos@b2stage-centos ~]$ globus-url-copy -list gsiftp://b2stage-centos/b2stageZone/home/b2stage/
gsiftp://b2stage-centos/b2stageZone/home/b2stage/


error: globus_ftp_client: the server responded with an error
530 530-Login incorrect. : /home/admincentos/B2STAGE-GridFTP/DSI/globus_gridftp_server_iRODS.c:globus_l_gfs_iRODS_start:700:
530-rcConnect failed:: _rcConnect: connectToRhost failed
530- Host: 'b2stage-centos', Port: '1247', UserName 'b2stage', Zone 'b2stageZone'
530-
530 End.
```

I checked:
- gridmap file maps correctly to the iRODS user
- User who runs gridFTP can login to iRODS

The errors apply both to iRODS 4.1.10 run on Ubuntu 14/16 and CentOS7.3

Any help is appreciated. I attach a full description on how I built the gridFTP server.
Many thanks,
Christine
[B2STAGE on CentOS 7.3.pdf](https://github.com/EUDAT-B2STAGE/B2STAGE-GridFTP/files/1526286/B2STAGE.on.CentOS.7.3.pdf)

**Comment by sararkd** [comment]
Hello! 
Installing the B2STAGE DSI on a CentOS 7 with iRODS 4.1.10, I also got the same errors and fixed them as Christine did. 

In the end I got the error below.
It seems like I can't go ahead on this configuration. 
Will try to use an older version of the B2STAGE DSI, but that shoulen'd be the solution here. 

I'd very much appreciate if anyone could help with this.

```
$ globus-url-copy -dbg -list gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/
gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/
debug: starting to feat gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/
debug: connecting to gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/
debug: response from gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/:
220 localhost GridFTP Server 12.4 (gcc64, 1510152968-85) [Globus Toolkit 6.0] ready.

debug: authenticating with gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/
debug: response from gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/:
530-Login incorrect. : /var/lib/irods/iRODS_DSI/B2STAGE-GridFTP/DSI/globus_gridftp_server_iRODS.c:globus_l_gfs_iRODS_make_error:580:
530-iRODS DSI. Error: 'clientLogin' failed.. CAT_INVALID_AUTHENTICATION: , status: -826000.
530-
530 End.

debug: fault on connection to gsiftp://145.100.58.129.surf-hosted.nl/homeZone/home/sara/
debug: operation complete


error: globus_ftp_client: the server responded with an error
530 530-Login incorrect. : /var/lib/irods/iRODS_DSI/B2STAGE-GridFTP/DSI/globus_gridftp_server_iRODS.c:globus_l_gfs_iRODS_make_error:580:
530-iRODS DSI. Error: 'clientLogin' failed.. CAT_INVALID_AUTHENTICATION: , status: -826000.
530-
530 End.
```

**Comment by chStaiger** [comment]
I see right now. I missed to add 

```sh
$HOME /root
```
to the server config.
Many thanks @muccix.

It works now.
